/*
 Navicat Premium Data Transfer

 Source Server         : localhost_MySQL
 Source Server Type    : MySQL
 Source Server Version : 50721
 Source Host           : localhost:3306
 Source Schema         : rcm

 Target Server Type    : MySQL
 Target Server Version : 50721
 File Encoding         : 65001

 Date: 09/02/2018 14:48:29
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for authorities
-- ----------------------------
DROP TABLE IF EXISTS `authorities`;
CREATE TABLE `authorities`  (
  `username` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `authority` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  INDEX `fk_authorities_users_idx`(`username`) USING BTREE,
  INDEX `ix_auth_username`(`username`, `authority`) USING BTREE,
  CONSTRAINT `fk_authorities_users` FOREIGN KEY (`username`) REFERENCES `users` (`username`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = 'create table authorities (\n	username varchar_ignorecase(50) not null,\n	authority varchar_ignorecase(50) not null,\n	constraint fk_authorities_users foreign key(username) references users(username)\n);\ncreate unique index ix_auth_username on authorities (username,authority);' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for group_authorities
-- ----------------------------
DROP TABLE IF EXISTS `group_authorities`;
CREATE TABLE `group_authorities`  (
  `group_id` bigint(20) NOT NULL,
  `authority` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  INDEX `fk_group_authorities_group_idx`(`group_id`) USING BTREE,
  CONSTRAINT `fk_group_authorities_group` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = 'create table group_authorities (\n	group_id bigint not null,\n	authority varchar(50) not null,\n	constraint fk_group_authorities_group foreign key(group_id) references groups(id)\n);' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for group_members
-- ----------------------------
DROP TABLE IF EXISTS `group_members`;
CREATE TABLE `group_members`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `group_id` bigint(20) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `fk_group_members_group_idx`(`group_id`) USING BTREE,
  CONSTRAINT `fk_group_members_group` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = 'create table group_members (\n	id bigint generated by default as identity(start with 0) primary key,\n	username varchar(50) not null,\n	group_id bigint not null,\n	constraint fk_group_members_group foreign key(group_id) references groups(id)\n);' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for groups
-- ----------------------------
DROP TABLE IF EXISTS `groups`;
CREATE TABLE `groups`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `group_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = 'create table groups (\n	id bigint generated by default as identity(start with 0) primary key,\n	group_name varchar_ignorecase(50) not null\n);' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for persistent_logins
-- ----------------------------
DROP TABLE IF EXISTS `persistent_logins`;
CREATE TABLE `persistent_logins`  (
  `username` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `series` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `token` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `last_used` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0),
  PRIMARY KEY (`series`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = 'create table persistent_logins (\n	username varchar(64) not null,\n	series varchar(64) primary key,\n	token varchar(64) not null,\n	last_used timestamp not null\n);' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for process_risk_source
-- ----------------------------
DROP TABLE IF EXISTS `process_risk_source`;
CREATE TABLE `process_risk_source`  (
  `process_id` bigint(20) NOT NULL,
  `source_id` bigint(20) NOT NULL,
  INDEX `fk_process_risk_source_process_idx`(`process_id`) USING BTREE,
  INDEX `fk_process_risk_source_source_idx`(`source_id`) USING BTREE,
  CONSTRAINT `fk_process_risk_source` FOREIGN KEY (`source_id`) REFERENCES `risk_source` (`source_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_task_process_risk_source` FOREIGN KEY (`process_id`) REFERENCES `task_process` (`process_id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '工序\n危险源' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for risk_source
-- ----------------------------
DROP TABLE IF EXISTS `risk_source`;
CREATE TABLE `risk_source`  (
  `source_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `risk_source` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '危险源',
  `hazard_factor` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '危害因素',
  `hazard_consequence` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '危害后果',
  `possibility` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '可能性',
  `accident_level` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '事故等级',
  `risk_level` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '风险等级',
  `work_standards` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '作业标准',
  PRIMARY KEY (`source_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '危险源' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for rpc_ticket
-- ----------------------------
DROP TABLE IF EXISTS `rpc_ticket`;
CREATE TABLE `rpc_ticket`  (
  `ticket_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `ticket_name` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `task_id` bigint(20) NULL DEFAULT NULL,
  `task_name` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `created_time` datetime(0) NULL DEFAULT NULL,
  `created_user` bigint(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ticket_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '风险预控票\nrisk_pre_control_ticket' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for task_process
-- ----------------------------
DROP TABLE IF EXISTS `task_process`;
CREATE TABLE `task_process`  (
  `process_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `task_process` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`process_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '工序' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for ticket_detail
-- ----------------------------
DROP TABLE IF EXISTS `ticket_detail`;
CREATE TABLE `ticket_detail`  (
  `detail_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `ticket_id` bigint(20) NULL DEFAULT NULL,
  `process_id` bigint(20) NULL DEFAULT NULL,
  `task_process` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `source_id` bigint(20) NULL DEFAULT NULL,
  `risk_source` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `hazard_factor` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `hazard_consequence` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `possibility` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `accident_level` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `risk_level` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `work_standards` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  PRIMARY KEY (`detail_id`) USING BTREE,
  INDEX `fk_rpc_ticket_detail`(`ticket_id`) USING BTREE,
  INDEX `fk_ticket_detail_task_process`(`process_id`) USING BTREE,
  INDEX `fk_ticket_detail_risk_source`(`source_id`) USING BTREE,
  CONSTRAINT `fk_rpc_ticket_detail` FOREIGN KEY (`ticket_id`) REFERENCES `rpc_ticket` (`ticket_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_ticket_detail_risk_source` FOREIGN KEY (`source_id`) REFERENCES `risk_source` (`source_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_ticket_detail_task_process` FOREIGN KEY (`process_id`) REFERENCES `task_process` (`process_id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users`  (
  `username` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `password` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  PRIMARY KEY (`username`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = 'create table users(\n	username varchar_ignorecase(50) not null primary key,\n	password varchar_ignorecase(50) not null,\n	enabled boolean not null\n);' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for work_task
-- ----------------------------
DROP TABLE IF EXISTS `work_task`;
CREATE TABLE `work_task`  (
  `task_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `work_task` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`task_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '工作任务' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for work_task_process
-- ----------------------------
DROP TABLE IF EXISTS `work_task_process`;
CREATE TABLE `work_task_process`  (
  `task_id` bigint(20) NOT NULL,
  `process_id` bigint(20) NOT NULL,
  INDEX `fk_work_task_process_2_idx`(`process_id`) USING BTREE,
  INDEX `fk_work_task_process_1_idx`(`task_id`) USING BTREE,
  CONSTRAINT `fk_work_task_process_1` FOREIGN KEY (`task_id`) REFERENCES `work_task` (`task_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_work_task_process_2` FOREIGN KEY (`process_id`) REFERENCES `task_process` (`process_id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '工作任务\n工序' ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
